# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='added_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
