# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sale_amount'),
        ('activity', '0005_conclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField(default=datetime.date.today)),
                ('places', models.TextField(blank=True)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Rep')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('outstanding', models.IntegerField(default=0)),
                ('report', models.TextField(blank=True)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Rep')),
            ],
        ),
    ]
