# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rep_supervisor'),
        ('activity', '0007_auto_20160428_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='activity',
        ),
        migrations.AddField(
            model_name='competition',
            name='competing_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='competition',
            name='competing_product',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='competition',
            name='expected_effect',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='competition',
            name='suggestion',
            field=models.TextField(blank=True),
        ),
    ]
