# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20160517_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='activity',
            field=models.TextField(blank=True),
        ),
    ]
