# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rep_supervisor'),
        ('activity', '0009_competition_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_value', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='call',
            name='order_value',
        ),
        migrations.RemoveField(
            model_name='call',
            name='products_detailed',
        ),
        migrations.AddField(
            model_name='call',
            name='next_meeting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Call'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
