# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20160520_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['recorded_date', 'time_slot'], 'verbose_name_plural': 'Itinerary'},
        ),
    ]
