# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rep_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
