# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_payment_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.PositiveIntegerField(choices=[(0, 'Hospital'), (1, 'Institution'), (2, 'Pharmacy'), (3, 'Wholeseller'), (4, 'Health Personnel')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_date',
            field=models.DateField(default=datetime.date(2016, 4, 29)),
            preserve_default=False,
        ),
    ]
