# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20160429_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode_of_payment',
            field=models.PositiveIntegerField(choices=[(0, 'E-Payment'), (1, 'Cheque'), (2, 'Teller')], default=0),
            preserve_default=False,
        ),
    ]
