# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_payment_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='teller_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='teller_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
