# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20160429_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
