# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20160429_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_type',
            field=models.PositiveIntegerField(choices=[(0, 'Actual Sales'), (1, 'SOR'), (2, 'Samples')], default=0),
            preserve_default=False,
        ),
    ]
