# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 04:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_sale_sales_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=200)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('sales_type', models.PositiveIntegerField(choices=[(0, 'Actual Sales'), (1, 'SOR'), (2, 'Samples')])),
                ('recorded_date', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to='product.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_invoices', to='product.Product')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_invoices', to='product.Rep')),
            ],
        ),
    ]
