# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_batchsize_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sales_type',
        ),
        migrations.AddField(
            model_name='sale',
            name='batch_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.BatchSize'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sales', to='product.Invoice'),
        ),
    ]
