# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20160430_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.PriceTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='template',
            field=models.ManyToManyField(through='product.ProductPriceTemplate', to='product.PriceTemplate'),
        ),
    ]
