# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20160430_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_of_payment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
