# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20160502_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Rep'),
        ),
    ]
