# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rep_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
