# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_sale_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('products_detailed', models.TextField(blank=True)),
                ('order_value', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('call_type', models.PositiveIntegerField(choices=[(0, 'Government'), (1, 'Private'), (2, 'Trade Calls')])),
                ('call_date', models.DateField()),
                ('recorded_date', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Customer')),
            ],
        ),
    ]
