# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sale_amount'),
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='rep',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.Rep'),
            preserve_default=False,
        ),
    ]
